import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='CategoryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Categoria principal', max_length=50)),
                ('subcategory', models.CharField(help_text='Subcategoria', max_length=100)),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total de emails nesta categoria')),
                ('last_7_days', models.PositiveIntegerField(default=0, help_text='Emails nos últimos 7 dias')),
                ('last_30_days', models.PositiveIntegerField(default=0, help_text='Emails nos últimos 30 dias')),
                ('avg_confidence', models.FloatField(default=0.0, help_text='Confiança média da categoria')),
                ('avg_processing_time', models.FloatField(default=0.0, help_text='Tempo médio de processamento (ms)')),
                ('trend_direction', models.CharField(choices=[('increasing', 'Crescendo'), ('decreasing', 'Diminuindo'), ('stable', 'Estável')], default='stable', help_text='Direção da tendência', max_length=20)),
                ('trend_percentage', models.FloatField(default=0.0, help_text='Percentual da mudança')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Statistics',
                'verbose_name_plural': 'Category Statistics',
                'ordering': ['-total_count'],
                'unique_together': {('category', 'subcategory')},
            },
        ),
        migrations.CreateModel(
            name='EmailAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_email', models.EmailField(blank=True, help_text='Email do remetente', max_length=254, null=True)),
                ('sender_name', models.CharField(blank=True, help_text='Nome do remetente', max_length=200, null=True)),
                ('sender_domain', models.CharField(blank=True, help_text='Domínio do remetente', max_length=100, null=True)),
                ('category', models.CharField(help_text='Categoria principal: Produtivo/Improdutivo', max_length=50)),
                ('subcategory', models.CharField(help_text='Subcategoria detalhada', max_length=100)),
                ('tone', models.CharField(help_text='Tom: Positivo/Negativo/Neutro', max_length=30)),
                ('urgency', models.CharField(help_text='Urgência: Alta/Média/Baixa', max_length=30)),
                ('confidence_score', models.FloatField(help_text='Score de confiança da classificação (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('word_count', models.PositiveIntegerField(help_text='Número de palavras do email')),
                ('char_count', models.PositiveIntegerField(help_text='Número de caracteres')),
                ('has_attachments', models.BooleanField(default=False, help_text='Possui anexos mencionados')),
                ('attachment_score', models.IntegerField(default=0, help_text='Score da análise de anexos')),
                ('keywords_detected', models.JSONField(default=list, help_text='Lista de palavras-chave encontradas no email')),
                ('processing_time_ms', models.PositiveIntegerField(default=0, help_text='Tempo de processamento em milissegundos')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp do processamento')),
                ('email_date', models.DateTimeField(blank=True, help_text='Data original do email', null=True)),
                ('source', models.CharField(choices=[('single', 'Processamento Individual'), ('batch', 'Processamento em Lote'), ('api', 'API Externa')], default='single', help_text='Origem do processamento', max_length=50)),
                ('technical_data', models.JSONField(default=dict, help_text='Dados técnicos adicionais (IPs, headers, etc.)')),
            ],
            options={
                'verbose_name': 'Email Analytics',
                'verbose_name_plural': 'Email Analytics',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['category'], name='analytics_e_categor_3ae3f3_idx'), models.Index(fields=['subcategory'], name='analytics_e_subcate_c83ed0_idx'), models.Index(fields=['processed_at'], name='analytics_e_process_310ad7_idx'), models.Index(fields=['sender_domain'], name='analytics_e_sender__2cc0ec_idx'), models.Index(fields=['urgency'], name='analytics_e_urgency_702174_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Palavra-chave', max_length=100)),
                ('category', models.CharField(help_text='Categoria associada', max_length=50)),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Frequência total')),
                ('last_7_days_freq', models.PositiveIntegerField(default=0)),
                ('last_30_days_freq', models.PositiveIntegerField(default=0)),
                ('avg_confidence_when_present', models.FloatField(default=0.0, help_text='Confiança média quando esta palavra está presente')),
                ('contexts', models.JSONField(default=list, help_text='Contextos onde esta palavra aparece mais')),
                ('first_detected', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword Frequency',
                'verbose_name_plural': 'Keyword Frequencies',
                'ordering': ['-frequency'],
                'indexes': [models.Index(fields=['keyword'], name='analytics_k_keyword_88ffdf_idx'), models.Index(fields=['category'], name='analytics_k_categor_361696_idx'), models.Index(fields=['-frequency'], name='analytics_k_frequen_285598_idx')],
                'unique_together': {('keyword', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SenderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_identifier', models.CharField(help_text='Email ou domínio do remetente', max_length=200)),
                ('sender_type', models.CharField(choices=[('email', 'Email Específico'), ('domain', 'Domínio')], help_text='Tipo de identificador', max_length=20)),
                ('productive_count', models.PositiveIntegerField(default=0)),
                ('unproductive_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('productivity_rate', models.FloatField(default=0.0, help_text='Taxa de produtividade (%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('high_urgency_count', models.PositiveIntegerField(default=0)),
                ('medium_urgency_count', models.PositiveIntegerField(default=0)),
                ('low_urgency_count', models.PositiveIntegerField(default=0)),
                ('positive_tone_count', models.PositiveIntegerField(default=0)),
                ('negative_tone_count', models.PositiveIntegerField(default=0)),
                ('neutral_tone_count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(help_text='Primeiro email processado')),
                ('last_seen', models.DateTimeField(help_text='Último email processado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sender Statistics',
                'verbose_name_plural': 'Sender Statistics',
                'ordering': ['-productivity_rate', '-total_count'],
                'unique_together': {('sender_identifier', 'sender_type')},
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data de referência')),
                ('hour', models.PositiveIntegerField(default=0, help_text='Hora (0-23) para granularidade horária', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('total_emails', models.PositiveIntegerField(default=0)),
                ('productive_emails', models.PositiveIntegerField(default=0)),
                ('unproductive_emails', models.PositiveIntegerField(default=0)),
                ('high_urgency', models.PositiveIntegerField(default=0)),
                ('medium_urgency', models.PositiveIntegerField(default=0)),
                ('low_urgency', models.PositiveIntegerField(default=0)),
                ('positive_tone', models.PositiveIntegerField(default=0)),
                ('negative_tone', models.PositiveIntegerField(default=0)),
                ('neutral_tone', models.PositiveIntegerField(default=0)),
                ('productivity_rate', models.FloatField(default=0.0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('avg_processing_time', models.FloatField(default=0.0)),
                ('granularity', models.CharField(choices=[('hourly', 'Por Hora'), ('daily', 'Por Dia')], default='daily', max_length=10)),
            ],
            options={
                'verbose_name': 'Time Series Data',
                'verbose_name_plural': 'Time Series Data',
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['date'], name='analytics_t_date_7a4be8_idx'), models.Index(fields=['granularity'], name='analytics_t_granula_4ad025_idx')],
                'unique_together': {('date', 'hour', 'granularity')},
            },
        ),
    ]
