"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent



SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-my-test-key-for-development-12345')

DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'corsheaders',

    'classifier',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'



DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()

if DB_ENGINE == 'sqlite' or not DB_ENGINE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'email_classifier_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'connect_timeout': 10,
            }
        }
    }
else:
    raise ValueError(f"DB_ENGINE inválido: {DB_ENGINE}. Use 'sqlite' ou 'postgresql'")



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'classifier': {
            'handlers': ['console'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}



STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_NUMBER_FILES = 5

# Security settings para produção
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Cookies seguros apenas em produção
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True


USE_REDIS = os.getenv('USE_REDIS', 'False') == 'True'

if USE_REDIS:
    REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
            },
            'KEY_PREFIX': 'email_classifier',
            'TIMEOUT': 300,
        },
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'django_cache_table',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        },
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'

SESSION_CACHE_ALIAS = 'default'


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.middleware.authentication.OptionalAPIKeyAuthentication',
    ],

    'DEFAULT_THROTTLE_CLASSES': [
        'core.middleware.throttling.BurstRateThrottle',      
        'core.middleware.throttling.AnonRateThrottle',       
        'core.middleware.throttling.APIKeyRateThrottle',     
    ],
    'DEFAULT_THROTTLE_RATES': {
        'burst': '10/minute',        
        'anon': '50/hour',           
        'api_key': '1000/hour',
        'daily': '5000/day',        
    },
}


API_KEYS = os.getenv('API_KEYS', '').split(',') if os.getenv('API_KEYS') else [
    'dev_test_key_123',  
]


SPECTACULAR_SETTINGS = {
    'TITLE': 'Email Intelligence API',
    'DESCRIPTION': """

API completa para classificação inteligente de emails e analytics de produtividade.


**API Key via Header:**
```
X-API-Key: dev_test_key_123
```

**Rate Limits:**
- ✅ **COM API Key**: 1000 requests/hora
- ⚠️ **SEM API Key**: 50 requests/hora (apenas em desenvolvimento)
- 🚫 **Burst protection**: 10 requests/minuto (todos)

**Exemplo com cURL:**
```bash
curl -H "X-API-Key: dev_test_key_123" \\
     -H "Content-Type: application/json" \\
     -d '{"email_text": "Seu email aqui"}' \\
     http://localhost:8000/api/classifier/classify/
```


- Classificação automática por categoria e subcategoria
- Detecção de tom emocional (Positivo/Negativo/Neutro)
- Análise de urgência (Alta/Média/Baixa)
- Geração de resposta sugerida
- Análise de anexos mencionados
- Resumo executivo de emails longos
- Processamento em lote (até 50 emails)

- Métricas de produtividade em tempo real
- Tendências e gráficos temporais
- Análise de remetentes e domínios
- Insights de palavras-chave
- Métricas de performance do sistema
- Distribuição de categorias
- Lista paginada de emails processados


1. **Classificar um email único**:
   ```bash
   POST /classifier/classify/
   {
     "email_text": "Seu email aqui..."
   }
   ```

2. **Ver dashboard de produtividade**:
   ```bash
   GET /analytics/dashboard/overview/?days=30
   ```

3. **Processar emails em lote**:
   ```bash
   POST /classifier/batch/
   {
     "emails": ["email 1", "email 2", "email 3"]
   }
   ```


- **Swagger UI**: Interface interativa para testar endpoints
- **ReDoc**: Documentação detalhada alternativa
- **OpenAPI Schema**: Schema JSON para integração


- Repositório: https://github.com/CarlosVLemos/Email-verify-Backend
- Documentação completa: Ver arquivo API_ENDPOINTS.md
    """,
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'DEFAULT_GENERATOR_CLASS': 'drf_spectacular.generators.SchemaGenerator',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVE_AUTHENTICATION': None,
    
    # Silenciar warnings sobre autenticação customizada
    'ENUM_NAME_OVERRIDES': {},
    'POSTPROCESSING_HOOKS': [],
    'PREPROCESSING_HOOKS': [],
    'WARN_ON_ERROR': False,  # Desabilita warnings
    
    'SECURITY': [{'ApiKeyAuth': []}],
    
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'ApiKeyAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'X-API-Key',
                'description': 'API Key para autenticação (opcional em desenvolvimento)'
            }
        }
    },
    
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'tryItOutEnabled': True,
    },
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'SORT_OPERATIONS': False,
    'SCHEMA_PATH': '/tmp/schema.yml',  # Caminho com permissão para escrever
    'TAGS': [
        {'name': 'Email Classification', 'description': 'Endpoints para classificação e análise de emails'},
        {'name': 'Analytics Dashboard', 'description': 'Endpoints para métricas e insights de produtividade'},
        {'name': 'System', 'description': 'Endpoints de sistema e health check'},
        {'name': 'Hugging Face', 'description': 'Endpoints para integração com Hugging Face'},
    ],
}

CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS', 
    'http://localhost:3000,http://localhost:5173'
).split(',')

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]


SENTRY_DSN = os.getenv('SENTRY_DSN')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=1.0,
        send_default_pii=True,
        environment='production' if not DEBUG else 'development',
    )
